from pathlib import Path

base = Path(r"D:/AI/TrendRadar")
paths = [
    base / "trendradar/i18n/catalog_vi_vn.py",
    base / "trendradar/i18n/catalog_en.py",
    base / "trendradar/i18n/catalog_zh_cn.py",
]

entries = {
    "mcp.analytics.alert.high": "High",
    "mcp.analytics.alert.medium": "Medium",
    "mcp.analytics.error.entity_not_found": "Entity not found: {entity}",
    "mcp.analytics.error.entity_not_found_suggestion": "Check entity type and spelling, then retry",
    "mcp.analytics.error.invalid_analysis_type": "Invalid analysis type: {analysis_type}",
    "mcp.analytics.error.invalid_entity_type": "Invalid entity type: {entity_type}",
    "mcp.analytics.error.invalid_insight_type": "Invalid insight type: {insight_type}",
    "mcp.analytics.error.invalid_period_format": "Invalid period format",
    "mcp.analytics.error.invalid_period_format_suggestion": "Use preset period (today/yesterday/last_week/this_week/last_month/this_month) or {'start':'YYYY-MM-DD','end':'YYYY-MM-DD'}",
    "mcp.analytics.error.invalid_report_type": "Invalid report type: {report_type}",
    "mcp.analytics.error.no_related_news": "No related news found in {time_desc}",
    "mcp.analytics.error.no_related_news_suggestion": "Try broader date range or another entity/topic",
    "mcp.analytics.error.no_similar_news": "No similar news found (threshold {threshold})",
    "mcp.analytics.error.no_similar_news_suggestion": "Lower similarity threshold or expand time range",
    "mcp.analytics.error.no_today_data": "No data available today",
    "mcp.analytics.error.no_today_data_suggestion": "Run crawl first or choose a date with available data",
    "mcp.analytics.error.supported_analysis_types": "Supported analysis types: trend, lifecycle, viral, predict",
    "mcp.analytics.error.supported_compare_types": "Supported compare types: overview, topic_shift, platform_activity",
    "mcp.analytics.error.supported_entity_types": "Supported entity types: person, company, location, organization, product",
    "mcp.analytics.error.supported_insight_types": "Supported insight types: platform_compare, platform_activity, keyword_cooccur",
    "mcp.analytics.error.supported_report_types": "Supported report types: daily, weekly",
    "mcp.analytics.error.topic_not_found_in_range": "Topic '{topic}' not found in {time_desc}",
    "mcp.analytics.error.topic_not_found_in_range_suggestion": "Try another topic or extend date range",
    "mcp.analytics.error.unsupported_compare_type": "Unsupported compare type: {compare_type}",
    "mcp.analytics.error.unsupported_granularity": "Unsupported granularity: {granularity}",
    "mcp.analytics.error.unsupported_granularity_suggestion": "Only 'day' is currently supported",
    "mcp.analytics.label.new_topic": "New",
    "mcp.analytics.lifecycle.declining": "Declining",
    "mcp.analytics.lifecycle.rising": "Rising",
    "mcp.analytics.lifecycle.stable": "Stable",
    "mcp.analytics.lifecycle.surging": "Surging",
    "mcp.analytics.message.no_news_data": "No news data available",
    "mcp.analytics.message.no_viral_topics": "No viral topics detected (threshold: {threshold})",
    "mcp.analytics.note.deduplicated_less_than_limit": "Results were deduplicated; fewer items than limit may be returned",
    "mcp.analytics.note.only_found_matches": "Only {count} matched items found",
    "mcp.analytics.note.prediction_disclaimer": "Prediction is heuristic and for reference only",
    "mcp.analytics.note.send_ai_prompt": "Use the AI prompt field below to continue deeper analysis",
    "mcp.analytics.note.similar_limited": "Only top {count} similar groups shown (threshold: {threshold})",
    "mcp.analytics.prediction.rising_hot": "Likely to keep rising",
    "mcp.analytics.report.footer.generated_by": "Generated by TrendRadar",
    "mcp.analytics.report.label.appeared_n_times": "Appeared {count} times",
    "mcp.analytics.report.label.continued_hot": "Continued hot topics",
    "mcp.analytics.report.label.generated_at": "Generated at",
    "mcp.analytics.report.label.hot_keywords": "Hot keywords",
    "mcp.analytics.report.label.news_count": "News count: {count}",
    "mcp.analytics.report.label.platforms_covered": "Platforms covered",
    "mcp.analytics.report.label.report_date": "Report date",
    "mcp.analytics.report.label.total_news": "Total news",
    "mcp.analytics.report.label.weekly_continued_topics": "Weekly continued topics",
    "mcp.analytics.report.section.overview": "Overview",
    "mcp.analytics.report.section.platform_activity": "Platform activity",
    "mcp.analytics.report.section.selected_samples": "Selected samples",
    "mcp.analytics.report.section.top_topics": "Top topics",
    "mcp.analytics.report.section.trend_analysis": "Trend analysis",
    "mcp.analytics.report.title.daily": "Daily trend report",
    "mcp.analytics.report.title.weekly": "Weekly trend report",
    "mcp.analytics.summary.cross_platform_aggregation": "Cross-platform aggregated similar news",
    "mcp.analytics.summary.entity_related_news": "News related to {entity}",
    "mcp.analytics.summary.keyword_cooccurrence": "Keyword co-occurrence analysis",
    "mcp.analytics.summary.period_compare": "Period comparison analysis ({compare_type})",
    "mcp.analytics.summary.predicted_topics": "Predicted trending topics",
    "mcp.analytics.summary.sentiment_prompt": "Sentiment analysis prompt",
    "mcp.analytics.summary.similar_news": "Similar news clustering",
    "mcp.analytics.summary.topic_trend": "Topic trend analysis for '{topic}'",
    "mcp.analytics.summary.viral_detection": "Viral topic detection",
    "mcp.analytics.topic_type.flash_in_pan": "Flash in pan",
    "mcp.analytics.topic_type.periodic_hot": "Periodic hot",
    "mcp.analytics.topic_type.sustained_hot": "Sustained hot",
    "mcp.analytics.trend.down": "Down",
    "mcp.analytics.trend.stable": "Stable",
    "mcp.analytics.trend.up": "Up",
    "mcp.article.error.empty_url_list": "URL list cannot be empty",
    "mcp.article.error.empty_url_list_suggestion": "Provide at least one valid URL",
    "mcp.article.error.invalid_url": "Invalid URL: {url}",
    "mcp.article.error.invalid_url_suggestion": "URL must start with http:// or https://",
    "mcp.article.error.rate_limited": "Request rate limited by upstream service",
    "mcp.article.error.rate_limited_suggestion": "Wait a moment or configure Jina API key for higher limits",
    "mcp.article.error.timeout": "Request timed out ({timeout}s)",
    "mcp.article.error.timeout_suggestion": "Increase timeout or retry later",
    "mcp.article.note.batch_skipped": "Skipped {skipped} URLs (max batch size: {max_batch})",
    "mcp.article.summary.batch_result": "Batch article reading result",
    "mcp.search.error.custom_range_missing": "Custom time range requires both start_date and end_date",
    "mcp.search.error.custom_range_missing_suggestion": "Provide start_date and end_date in YYYY-MM-DD format",
    "mcp.search.error.invalid_search_mode": "Invalid search mode: {mode}",
    "mcp.search.error.invalid_sort_by": "Invalid sort_by: {sort_by}",
    "mcp.search.error.no_data_available": "No data available in selected range",
    "mcp.search.error.no_data_available_suggestion": "Try a wider range or run crawl first",
    "mcp.search.error.no_keywords_extracted": "No keywords could be extracted",
    "mcp.search.error.no_keywords_extracted_suggestion": "Try a different query or broaden the range",
    "mcp.search.error.supported_search_modes": "Supported search modes: exact, fuzzy",
    "mcp.search.error.supported_sort_by": "Supported sort_by: relevance, time, weight",
    "mcp.search.error.supported_time_preset": "Supported time presets: today, yesterday, last_3_days, last_7_days, last_30_days, custom",
    "mcp.search.error.unsupported_time_preset": "Unsupported time preset: {preset}",
    "mcp.search.message.no_match": "No matching news found in {time_desc}",
    "mcp.search.message.no_match_with_available": "No match found in {time_desc}. Available dates: {available_desc}",
    "mcp.search.message.no_related_news": "No related news found",
    "mcp.search.note.fuzzy_limited": "Only top {count} fuzzy matches returned (threshold: {threshold})",
    "mcp.search.note.related_limited": "Only top {count} related results returned (threshold: {threshold})",
    "mcp.search.summary.history_related_result": "Historical related-news results",
    "mcp.search.summary.news_result": "News search result ({mode})",
    "mcp.search.summary.related_result": "Related-news analysis result",
    "mcp.search.time.range": "{start} to {end}",
    "mcp.search.time.today": "today",
    "mcp.search.warning.process_date_failed": "Failed to process date {date}: {error}",
    "mcp.storage.error.remote_backend_failed": "Failed to initialize remote storage backend",
    "mcp.storage.error.remote_backend_failed_suggestion": "Check dependency installation and remote storage configuration",
    "mcp.storage.error.remote_not_configured": "Remote storage is not configured",
    "mcp.storage.error.remote_not_configured_suggestion": "Configure storage.remote in config or set S3_* environment variables",
    "mcp.storage.message.sync_result": "Sync completed: synced {synced}, skipped {skipped}, failed {failed}",
    "mcp.storage.summary.available_dates": "Available date list",
    "mcp.storage.summary.status": "Storage status",
    "mcp.storage.summary.sync_result": "Remote sync result",
}

for p in paths:
    content = p.read_text(encoding="utf-8").rstrip()
    lines = []
    for k, v in entries.items():
        if f'"{k}": ' not in content:
            vv = v.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    "{k}": "{vv}",')

    if not lines:
        print(p.name, "added", 0)
        continue

    if content.endswith("}"):
        content = content[:-1].rstrip()
    if not content.endswith(","):
        content += ","

    content += "\n\n" + "\n".join(lines) + "\n}\n"
    p.write_text(content, encoding="utf-8")
    print(p.name, "added", len(lines))
